version: "3"

services:
    os-monitor-app:
        # use Dockerfile in this context repo
        build: .
        restart: always
        environment:
            FLASK_APP: "app.py"
            FLASK_ENV: "development"
            FLASK_RUN_PORT: "5000"
        ports:
            - "5000:5000"
        volumes:
            - ${OS_MONITOR_OUTPUT}:/os-monitor/output
            - ./logs:/app/logs

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                # use this specific subnet to avoid interfere with company subnet.
                # The default one is 172.17.x.x and this was used already in company.
                - subnet:  192.168.123.0/24
