version: "3.3"

services:
    os-monitor-app:
        # use Dockerfile in this context repo
        build: .
        restart: always
        # --------------------------------------------------
        environment:
            FLASK_APP: "app.py"
            FLASK_ENV: "development"
            FLASK_RUN_PORT: "5001"
        # --------------------------------------------------
        ports:
            - "5001:5001"
        # --------------------------------------------------
        volumes:
            - ${OS_MONITOR_OUTPUT}:/os-monitor/output
            - ./logs:/app/logs
        # --------------------------------------------------
        deploy:
            resources:
                limits:
                    cpus: '0.60'
                    memory: 1G
                reservations:
                    cpus: '0.30'
                    memory: 100M

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                # use this specific subnet to avoid interfere with company subnet.
                # The default one is 172.17.x.x and this was used already in company.
                - subnet:  192.168.125.0/24
