version: "3.3"

services:

    # web server
    os-monitor-app:

        container_name: os-monitor-app

        build: ./app

        restart: always

        # main command for gunicorn production deploy.
        # change the port number of the app if needed.
        command:
            gunicorn os_monitor.wsgi --bind 0.0.0.0:5001

        # --------------------------------------------------
        expose:
            - 5001
        # --------------------------------------------------
        volumes:
            - ./app/os_monitor/static:/home/app/web/static
            - ${OS_MONITOR_OUTPUT}:/os-monitor/output
            - ./logs:/home/app/web/logs
        # --------------------------------------------------
        # docker-compose does not support 'deploy' keyword
        # in regular 'up' 'down' controls. Reserved for SWARM.
        # but calling docker-compose --compatibility make it work.
        # https://github.com/docker/compose/pull/5684
        # --------------------------------------------------
        deploy:
            resources:
                limits:
                    cpus: '0.60'
                    memory: 1G
                reservations:
                    cpus: '0.30'
                    memory: 100M

    # reverse-proxy
    nginx:
        container_name: nginx
        restart: always
        build: ./nginx
        ports:
            - "8000:80"
        depends_on:
            - os-monitor-app
        volumes:
            - ./app/os_monitor/static:/home/app/web/static

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                # use this specific subnet to avoid interfere with company subnet.
                # The default one is 172.17.x.x and this was used already in company.
                - subnet:  192.168.125.0/24
